### PR TITLE
Decentralized Treasury Model

### PR DESCRIPTION
**Pull request by cryptoguard**
---
layout: fr
network_vote: yes
title: Decentralized Treasury Model
author: Cryptoguard
date: May 14, 2021
amount: 1 PART
milestones:
  - name: Introduce a decentralized treasury model and treasury fund
    funds: 100% (1 PART)
    done:
    status: unfinished
payouts:
  - date:
    amount:
---

# Summary

This proposal introduces a new decentralized treasury model to support, promote, and expand Particl into a stronger-than-ever ecosystem. This will be accomplished by raising both the yearly staking reward rate and the developer block rewards, which will now be referred to as the "treasury block rewards". All the treasury block rewards will then be automatically deposited, by the protocol, into a Treasury Fund.

Anyone can claim funds from the Treasury Fund to support initiatives by publishing proposals on the CCS and get them approved by the stakeholders using on-chain voting.

# Rationale

As of November 2020, after slightly more than three years, the Particl Foundation has run out of the funds it raised from community donations and, as such, has left the Particl project with no funds to work with.

With today's fast-paced and rapidly evolving blockchain industry, any serious project needs to ensure it has enough funding to support its ecosystem, promote its product(s), and grow its community.

To address this critical issue, the Particl team has consulted with a few advisors and community leaders and put together a proposal for a new **decentralized treasury model** that, if approved by the Particl stakeholders, would **bring enough funding to self-sustain the project at current prices, boost community resources, and provide a brand new legal entity to support the project.**

# The Treasury Model in Detail

* Proposed yearly coin emission rate: **8%**
* Proposed treasury block rewards: **50%**
* Proposed total yearly staking rate (APR for stakers): **4%**

This proposal suggests increasing the yearly coin emission (staking) rate from **2% to 8%** for two years and then **decreasing it by 1% every two years** until it reaches **6% and stays at that level**. Every time the network stakes a block, **50% of the block rewards** would then be redistributed to stakers and **the other 50%, into the Treasury Fund** to fund, support, promote, and grow the project. That amounts to 4% of the total circulating supply every year.

This brings the **yearly PART coin emission (staking) interest (APY) to a minimum of 4%**. Because APY depends on how many coins are staking on the network, the true APY always ends up being higher than its minimum rate. For example, **if 50%** of all the PART coins are staking on the network, the **staking APY goes from 4% to around 8% yearly**.

* **Note:** _Once the yearly coin emission (staking) rate reaches 6%, it will remain at that level for as long as no other CCS proposal gets pushed and approved by the community._

## Self-Sustainability

This proposed treasury model is all about self-sustainability. Indeed, after the team claims funds from it, it will provide enough funding to cover salaries for the core team, pay for all related expenses, and fund various promotional budgets at current (and lower) PART prices. 

It also gives the extra resources required to expand the team with more talents and add more expertise to the table. More details on the internal restructuring of the team and how it intends to claim and use those funds will be provided in a separate proposal if and after this proposal is approved.

During its first year, the Treasury Fund would earn an **average of 39,166 PART every month**. At current price levels, this is sufficient to sustain the project and fund various initiatives to take Particl to the next level. The proposed model is viable down to a PART price of around $0.50.

Of course, the Treasury Fund exclusively gets funded with PART. An increase in the trading value of the coin would then make the incoming treasury fund claims more valuable in fiat, allowing the team (and anyone else that claims funds from it) to expand further, fund more initiatives/programs, stimulate the community to a greater degree, and accelerate the growth of the entire ecosystem even more.

# Proposal Approval and Treasury Governance

Particl stakeholders will have the final say over the governance and allocation of funds towards initiatives. 

To claim funds from the treasury, the Particl team, and any other party wishing to do so, will need to publish CCS proposals explaining the nature of the claim, how the funds are intended to be used, and what to expect in terms of deliverables. Then, the proposal will go into a voting period and will need to be approved by the stakeholders.

To favour flexibility, there are no set guidelines or rigid rules regarding what to put in such proposals. The only requirement for any proposal owner, aside from the fact that it needs to benefit the Particl ecosystem directly, is to make their proposal as straightforward as possible and to convince the stakeholders to vote in favour of the proposed idea.

* **To learn more about Particl’s on-chain voting system and how to submit and vote on CCS proposals, refer to [this Particl News blog post](https://particl.news/on-chain-voting-and-ccs-proposals/).**

# Timeframe

Because this proposal requires a protocol consensus vote (major change in the protocol), its voting phase will last for 10,080 blocks.

# Parties Involved

At every block, the protocol automatically deposits funds into a **3-of-5 multi-signature address managed by a few members of the Particl team**. Each signatory has agreed to execute payouts according to the results of proposal votes. 

Here are the signatories tasked with managing the treasury fund.

* **Tecnovert**
* **Gerlof van Ek (Crz)**
* **Cryptoguard**
* **Dasource**
* **Imran**

# FAQ

**Q:** Is the 10% Foundation donation being eliminated when the treasury model goes live?
**A:** Yes, the treasury model completely replaces the previous funding model.

**Q:** What happens to the treasury funds while they are not used? Are they staking?  Do they vote on proposals?
**A:** Unused treasury funds simply remain untouched in the Treasury Fund. They are not put up for staking or being used to vote on proposals. Any coin in the Treasury Fund cannot be used, transacted, or staked without the approval of stakeholders.

### CODE REVIEW

**Comment by AllienWorks** [comment]
> Q: What happens to the treasury funds while they are not used? Are they staking? Do they vote on proposals?

Agreed that coins shouldn't vote, but I think they should definitely stake. Fund will get more coins and securing the network with this (hopefully) always growing pile of coins is a must IMO.

Or what have I overlooked? Why have you decided not to stake them?

**Comment by btmr** [comment]
After reading this, two things remain unclear for me.
1. The treasury fund seems to be divided into a "development expenses" part that covers salaries, infrastructure expenses etc. and a remaining part that is reserved for initiatives that require community approval.
Given the proposed emission and the statement that this model is viable down to prices of 0.5 USD, I would assume projected dev costs to range somewhere between 15,000 and 20,000 USD per month. Correct? If the FIAT value of part increases, the monthly amount of PART available for initiatives will increase. Correct?

2. "More details on the internal restructuring of the team and how it intends to claim and use those funds will be provided in a separate proposal if and after this proposal is approved."

Shouldn't we know this before we cast our vote? Seems like a pretty important aspect of all this. Why not let us know now?

Cheers

**Comment by coybigpart** [comment]
Good proposal, I only want to suggest one little thing.
In my opinion a certain percentage of the Treasury Fund should always be reserved for the Particl Team for ongoing stuff where we don't have to vote for, but which they can use to their own insight at any (urgent) moment. For example:
- Maintenance
- Bug solving
- Keep up to date with the latest bitcoin version
- Refactoring
- Replace hardware

**Comment by coybigpart** [comment]
> > Q: What happens to the treasury funds while they are not used? Are they staking? Do they vote on proposals?
> 
> Agreed that coins shouldn't vote, but I think they should definitely stake. Fund will get more coins and securing the network with this (hopefully) always growing pile of coins is a must IMO.
> 
> Or what have I overlooked? Why have you decided not to stake them?

I agree, the Treasury Fund should be able to stake, but should not be able to vote.

**Comment by bacoinin** [comment]
Excellent proposal which not only covers the long-term funding for the project to thrive but also paves the way for Particl to become the world's first anonymous decentralized platform cooperative. I will strongly support the proposal.

My only future concern is that piling up a huge pile of coins that are under the control of a small group of individuals is a risk for the project. I hope in the future we can put a max cap on how much the Tresury fund can hold. For example, that limit could be set to x% of the total supply and if it is reached then the dev tax emissions could be auto-burned (with the total supply being auto-adjusted).

@coybigpart What you are suggesting can come as a 3/6 month budget and be approved by the stakeholders. Spending a few hours to prepare a budget is a very small price to pay to keep the control over the funds decentralized and in the hands of the stakeholders.

@AllienWorks The Treasury already gets the 50% of all the emissions, so if the fund starts staking then the total dev tax will become more than what the rest of the stakers get all together. Maybe If the dev tax was <50% of the total emission, staking those funds could make more sense. 

Personally I would rather that the Treasury fund coins are completely "locked/unused"  and that they can be only unlocked/used after the approval by the stakeholders. In otherwords, any transaction involving those funds that is not pre-approved via the on-chain voting should instantly raise level 5 red alert :D

**Comment by cryptoguard** [comment]
@AllienWorks 
> > Q: What happens to the treasury funds while they are not used? Are they staking? Do they vote on proposals?
> 
> Agreed that coins shouldn't vote, but I think they should definitely stake. Fund will get more coins and securing the network with this (hopefully) always growing pile of coins is a must IMO.
> 
> Or what have I overlooked? Why have you decided not to stake them?

and

@coybigpart 
> > > Q: What happens to the treasury funds while they are not used? Are they staking? Do they vote on proposals?
> > 
> > 
> > Agreed that coins shouldn't vote, but I think they should definitely stake. Fund will get more coins and securing the network with this (hopefully) always growing pile of coins is a must IMO.
> > Or what have I overlooked? Why have you decided not to stake them?
> 
> I agree, the Treasury Fund should be able to stake, but should not be able to vote.

The reason for not staking, at least initially, the Treasury Fund coins is to not create a staking "competition" between the Treasury Fund and individual stakers, especially as the treasury would already get 50% of all staking rewards emitted by the network. This could create a situation where stakeholders may be more likely to spend the funds (aka being less cautious about the spendings, less optimal) to prevent the treasury from accumulating more coins and thus, a greater staking power (which would reduce the yearly staking interest rate of other stakers).

That being said, it would have benefits, such as improving the stability and security of the network. We are not opposed to enabling staking on the Treasury Fund, but we think we should at least introduce the treasury as a non-staking fund and then push a separate proposal specifically to reach a decision on whether or not the funds should be staking. That way, people would be able to vote differently on the two proposals and not be force to accept both propositions at once. 

@coybigpart 

> Good proposal, I only want to suggest one little thing.
> In my opinion a certain percentage of the Treasury Fund should always be reserved for the Particl Team for ongoing stuff where we don't have to vote for, but which they can use to their own insight at any (urgent) moment. For example:
> 
>     * Maintenance
> 
>     * Bug solving
> 
>     * Keep up to date with the latest bitcoin version
> 
>     * Refactoring
> 
>     * Replace hardware

This is an interesting option which could be discussed in the next proposal we want to push if the treasury model proposal is approved. The reason we're separating the treasury fund proposal from the team funding claim proposal is to not tie the treasury model proposal with a claim of funds. We would rather have the community express their will exclusively on the concept of the treasury model first, and then push another proposal which will be all about the team claiming funding from the treasury to fund its operations and costs.

In other words, we don't want to force any team proposal through by holding stakeholders "hostage" through another proposal. This will let stakeholders vote differently, if they wish to, on the two proposals.

@btmr 

> After reading this, two things remain unclear for me.
> 
>     1. The treasury fund seems to be divided into a "development expenses" part that covers salaries, infrastructure expenses etc. and a remaining part that is reserved for initiatives that require community approval.
>        Given the proposed emission and the statement that this model is viable down to prices of 0.5 USD, I would assume projected dev costs to range somewhere between 15,000 and 20,000 USD per month. Correct? If the FIAT value of part increases, the monthly amount of PART available for initiatives will increase. Correct?
> 
>     2. "More details on the internal restructuring of the team and how it intends to claim and use those funds will be provided in a separate proposal if and after this proposal is approved."
> 
> 
> Shouldn't we know this before we cast our vote? Seems like a pretty important aspect of all this. Why not let us know now?
> 
> Cheers

More details about how the team intends on claiming and using funds from the Treasury Fund will be published if and after this proposal is approved. The reason for this is that one can be approved while the other can be rejected. We don't want to force stakeholders to accept the team funding proposal by accepting the treasury model proposal. They are two different proposals and the team will push its own funding proposals, like any other entity could, on the CCS to claim funds from it.

In other words, you could vote in favour of the treasury model proposal, but reject the team proposal. We don't want to force you to approve the team proposal if you only want to approve the treasury model proposal.

That being said, the team intends on growing and expanding as a result of this proposal, if approved of course. It also intends on ramping up marketing, user adoption, as well as build a coin reserve for things like partnerships, exchange listings, and other promotional efforts. For this reason, and due to the fluctuating price of PART, the amount of funding used by the team each month will vary. The team funding proposals will take this reality into consideration to ensure operations remain smooth regardless of market activity and also to reduce friction as much as is reasonably possible. We are ready to share those details as soon as this proposal is approved, but don't want to influence the outcome of this proposal by jumping the gun. We want stakeholders to express themselves freely exclusively on the concept of the treasury model without any other underlying caveat.

**Comment by cryptoguard** [comment]
@bacoinin 
> Excellent proposal which not only covers the long-term funding for the project to thrive but also paves the way for Particl to become the world's first anonymous decentralized platform cooperative. I will strongly support the proposal.
> 
> My only future concern is that piling up a huge pile of coins that are under the control of a small group of individuals is a risk for the project. I hope in the future we can put a max cap on how much the Tresury fund can hold. For example, that limit could be set to x% of the total supply and if it is reached then the dev tax emissions could be auto-burned (with the total supply being auto-adjusted).
> 
> @coybigpart What you are suggesting can come as a 3/6 month budget and be approved by the stakeholders. Spending a few hours to prepare a budget is a very small price to pay to keep the control over the funds decentralized and in the hands of the stakeholders.
> 
> @AllienWorks The Treasury already gets the 50% of all the emissions, so if the fund starts staking then the total dev tax will become more than what the rest of the stakers get all together. Maybe If the dev tax was <50% of the total emission, staking those funds could make more sense.
> 
> Personally I would rather that the Treasury fund coins are completely "locked/unused" and that they can be only unlocked/used after the approval by the stakeholders. In otherwords, any transaction involving those funds that is not pre-approved via the on-chain voting should instantly raise level 5 red alert :D

We would love to eventually decentralize most of the treasury model system and will look at how to achieve this in a later phase as we move forward. This would essentially fix that issue you mention regarding the team managing the treasury's coins (of course, always according to proposal voting results). For now, we are opting for a simpler approach to be able to move faster and initiate Particl's community governance journey swiftly.

**Comment by bacoinin** [comment]
> For now, we are opting for a simpler approach to be able to move faster and initiate Particl's community governance journey swiftly.
My concern was mostly a far future one (2+ years) so the current approach with a small team is a good all-arounder. 

As for the key-holders, I have not interacted with Imran and dasource so I practically do not know them but You, Tecnovert and Crz I trust pretty much unconditionally :D

**Comment by btmr** [comment]
@cryptoguard Thanks for clarifying. Maybe it's just because you spelled it out for me but I find it immensely valuable to get a bit more insight into the thinking behind these proposals.

Looking forward to voting on this

**Comment by coybigpart** [comment]
Thanks @cryptoguard ! Looking forward to vote for the proposal. I will support it!!! I'm sure many people will support it.

**Comment by coybigpart** [comment]
The transaction fees will all go to the miners no?

**Comment by dasource** [comment]
> The transaction fees will all go to the miners no?

Yes, only the block reward is changed. No changes to fees etc, they all go to the stakers.

**Pull request merged**
