### PR TITLE
Team Funding Proposal 2

### PR DESCRIPTION
**Pull request by cryptoguard**
# Summary

This proposal is a funding request by the Particl team. It requests **35,250 PART per month** from the treasury fund for a period of **6 months only** after which the team will submit a new funding request for a community vote. **The request follows a model in which PART is calculated at $1**.

### Note

This proposal is willingly kept brief for the purpose of the CCS system. For more details on this proposal and on how the team intends to strategically moving forward during the first half of 2022, check out the [Particl Team Funding Request #2](https://particl.news/team-funding-proposal-2/) blog post available on Particl News. 

# Rationale

The Particl team operates strictly on community donations as voted by Particl stakeholder every six months. Funding, in PART, is taken directly from the network’s treasury and allocated to the team to fund all operations. 

**With this proposal, the Particl team is formally requesting 35,250 PART coins per month from the treasury to fund development, marketing, user acquisition, business development, legal, corporate, and operational costs. The request covers all expected expenses for the next 6 months**.

# Funding Distribution

The funds claimed from the treasury by the Particl team will be used for various purposes, not just for development. The team intends to use these resources to strategically put the project in a better position, improve brand awareness, and attract new users to the ecosystem.

The funds will be approximately distributed as follows (more details about fund distribution here).

* **Development (60%)**, to fund the development of the Particl ecosystem and expand the current development team. Resources will also be allocated to work on various items other than Particl Core, Desktop, and Marketplace. This includes, but isn't limited to, Particl Copay, the SMSG network (SMSG 2.0), BasicSwap (atomic swap DEX), web and mobile platforms, and so on).

* **Marketing and community (20%)**, to increase Particl’s brand awareness and exposure within the cryptocurrency, blockchain, e-commerce, and other related industries. Also includes onboarding new community members, expanding on welcoming efforts on current platforms, as well as expanding social media communities. Includes promotion of the PART cryptocurrency, Particl Marketplace, BasicSwap (DEX), and any other upcoming Particl product.

* **Management, legal, and administration (10%)**, to fund any administrative or corporate costs (i.e., human resources, accounting, project management, legal costs, corporate fees, etc.).

* **Business development (10%)**, to pursue strategic opportunities, develop partnerships/relationships, and identify/capitalize on new markets for Particl's line of products. This also includes the advisory and exchange listing budgets.

For a more detailed breakdown of how the funds will be used, please refer to the in-depth blog post on this proposal available on Particl News ([click here](https://particl.news/team-funding-proposal-2/)).

### Note

Any unused PART will be safely deposited into the team’s reserves to provide funding for later or unforeseen expenses, or increase individual cost-related activities. Please note that the above distribution model is approximate and the team may rearrange it as needed.

# Legal Entity

All funds voted to be allocated to the Particl team are held and managed by SoonTM Development Ltd, a software development company registered by the team.

### CODE REVIEW

**Comment by rynomster** [comment]
The Funding Request link seems to be broken, it should be https://particl.news/particl-team-proposal-request-2/

**Comment by cryptoguard** [comment]
> The Funding Request link seems to be broken, it should be https://particl.news/team-funding-proposal-2/

Indeed, I've edited the link. Thanks for the notice!

**Comment by bacoinin** [comment]
@cryptoguard For the team funding proposal 1 your wrote:

"
At the time of this writing, we can confirm the following Particl team members to be taking part, full or part time, in this new Particl journey phase.

-     Cryptoguard — Project management and communications
-     Gerlof van Ek (crz) — Project and development management, Lead Designer, UI/UX, and front-end developer
-     Imran — Treasury and business management, strategic partnerships
-     Henk Swardt — Development management and coordinator
-     Tecnovert — Lead core developer
-     Arnold Bansemer — Lead desktop developer
-     Kewde — Marketplace developer, OMP, and core
-     Juha Kovanen — Marketplace developer
-     Martin — UI & UX integration and front-end developer
-     Dros — Marketing, branding, and business research & development
-     Dasource — Technical research & development

Note: More (or new) team members may soon join the ranks. This list represents the current situation at the time of writing this blog post.
"

Could you please confirm if possible that the team composition as specified above has not changed. Thank you in advance.

**Comment by cryptoguard** [comment]
@bacoinin

Yes, the list above is accurate. However, at this time, Juha and Martin are not fully active development-wise. We also have begun looking into adding new developers and we are onboarding one for a trial run starting starting next week!

**Pull request merged**
