### PR TITLE
Marketplace Listing Seeding Proposal

### PR DESCRIPTION
**Pull request by cryptoguard**
# Summary

Fund the development, maintenance, and management of an automated system to seed Particl Marketplace with thousands of products (and their reviews) and various storefronts. **The initiative aims at adding 5,000+ products to the Particl Marketplace** to kickstart V3 adoption and provide users with a vast selection of items at all times. However, **this 5,000 figure may vary depending on various factors** such as stability of the SMSG network, actual listing fees in a live environment, user experience, quality of content, etc. Additional listings (other than the initial 5,000+ listings) may be made available sometime after deployment if the automated system handles the throughput well.

The added products will be listed 24/7, their retail prices will be updated every day to account for the PART price volatility, and orders will be processed instantly and automatically via the system suggested in this proposal for the best user experience possible. Most products will be listed along with their (real) reviews taken from outside sources (i.e., straight from the supplier) and imported into Particl Desktop. The added storefronts will be automatically promoted for this proposal's entire duration to ensure they show on everybody's desktop application. 

# Rationale

Particl V3 is a massive technical milestone for the project. Its release brings on a much better desktop application with better performance, many more features, and a refreshed UI/UX. This proposed initiative is meant to support its release, kickstart its adoption, and complement future marketing and outreach efforts to make V3 much more impactful.

This proposal suggests community funding for the development, deployment, and management of an automated system to seed Particl Marketplace (v3) with thousands of products both horizontally (meaning from a lot of different categories) and vertically (meaning a lot of options in each selected category). 

Taking care of both the "verticality" and "horizontality" of products is very important for the user experience of any "marketplace for everything". Typically, when an online buyer shops on a marketplace for a specific type of product, they want to see as many options as possible. If you're looking for a USB key, for example, then you'd like to see many different brands with different amounts of storage capacity. If you're shopping for a camera, then you'd also want to see different types of cameras, brands, options, and so on. Of course, verticality and horizontality get better as more and more sellers start selling on the marketplace. Still, this initiative is meant to kickstart this dynamic, make it more appealing to start selling, make the marketplace more lively, and provide a good starting point in solving the chicken and egg problem.

## Key Points

Here are a few key points that provide more information about this initiative.

- Add roughly 5,000 products and various storefronts to the marketplace

- Automated and speedy processing of orders on Particl Desktop for the best user experience (few seconds between placing a bid and locking up escrow amount)

- Products are relisted every day to keep their prices in line with the ever-fluctuating PART price

- Products ship from different places (mostly USA, Europe, Russia, and China)

- Products are displayed along with their (real) reviews extracted directly from the supplier's store. Reviews will show up in the Question & Answer section of listing pages.

- Storefronts are always promoted within the Market Browser.

- The products are going to be dynamically managed to support and complement any marketing and outreach efforts. When the team or community targets a specific niche of users, products on the marketplace will be adjusted accordingly to reflect that.

- Any news and update (i.e., a change of strategy in the total number of listings) related to this initiative will be promptly communicated to the community.

## Benefits

This proposal is intended to enhance the user experience of Particl Marketplace, provide a part of the solution to fix the chicken and egg problem, and improve the success of any outreach and onboarding campaign. Here are, in more detail, some of the main benefits this proposal seeks to provide to the Particl ecosystem and community.

- **Better first impression**

You only get one shot at making a good first impression. A vibrant marketplace with thousands of items spread across many categories creates a much better first impression for anyone trying out Particl Marketplace for the first time. It also makes it much more likely that they will come back and use it again. 

- **Showcasing Storefronts**

This initiative will also lead to creating various storefronts that will be promoted in the Market Browser of Particl Marketplace. This will serve as a great showcase of the new functionality and will kickstart its usage. Various storefronts will be created, each with their unique theme and category of items, and will be promoted to the Market Browser for this proposal's entire duration. Every user can easily access them without having to look for their Market IDs manually.

- **Support user outreach**

Targeting vendors of specific niches is tricky when no other product within that niche already exists in the marketplace. That's because you're asking vendors to be first to list products within a specific category without guaranteeing a considerable number of buyers that come with it. Targeting buyers of specific niches is also tricky without a vast number of products within that category, for obvious reasons.

This proposal suggests pre-seeding the marketplace with a vast number of items related to any niche targeted by the Particl team or community. This will strengthen any outreach effort, help keep more users around, and give them a better reason to contribute with their own products.

- **Increase the number of on-chain transactions**

Listing thousands of items on the marketplace, and doing so every day, will increase the number of on-chain transactions due to listing fees being paid as well as whenever an item gets purchased. For example, 5,000 daily listings create, at a minimum, 5,000 transactions on the blockchain every day.

- **Improve the level of privacy on the network**

Any listing that gets bought creates a few RingCT transactions on the network, which increases the network's level of privacy. That's because it increases the total number of coins held in anon balances and generates more outputs (decoys) for private transactions. Adding 5,000+ products to the marketplace is highly likely to lead to an increase in the number of purchases, leading to a more robust and more private blockchain network.

To learn more about how the level of privacy can be enhanced through an increase in marketplace transactions, refer to the [Particl Explained - Private Transactions article](https://particl.news/particl-explained-private-transactions-44cb120d9cd).

- **Increase staking rewards**

Any product that gets listed on Particl Marketplace costs a small listing fee that is then redistributed to stakers. Listing thousands of items on the marketplace will directly lead to an increase in these staking rewards.

- **Create promotions**

Getting control of thousands of products on the marketplace opens up the door for many promotions, deals, specials, giveaways, and discounts. This can be used to promote the Particl Marketplace and platform on social media, when releasing news/features, and when targeting specific niches. 

There are many ways promotions can be run and attract new users that will, in turn, generate more organic activity on the marketplace. This system can also be used to help out any independent, community-based initiative. Simply contact Cryptoguard if you have an idea of how a particular promotion may help your project.

- **Speedy completion of orders**

As the entire buy flow and order processing system will be automated, any order the system receives will be processed very rapidly on Particl Marketplace and without requiring human intervention. This will significantly improve the user experience of the marketplace and lead to more people staying around after trying it for the first time. 

No more waiting hours or even days for the person you're transacting with to move and update an order. You'll be able to process through the entire initial phase of the buy flow (up until the seller ships the item) in just a few seconds.

# Timeframe

It's estimated that this initiative's development and deployment will take roughly four (4) weeks after this proposal moves to the Funding Required step of the CCS. If the system isn't ready by this time, an update will be communicated to the community.

## Note

This estimate does not constitute a deadline. Actual development time may be shorter or longer depending on various unpredictable factors. Some items (i.e., storefronts) may be delivered after the system's initial deployment so that it can go live more quickly with its basic functionality (seed listings and process orders).

# Duration of the Proposal

This proposal suggests deploying and then actively managing the initiative for six (6) months, after which the proposal may be renewed if deemed necessary. 

## Note

The product content strategy will actively be adapted throughout the duration of the initiative depending on the different marketing, outreach, and onboarding strategies adopted and the different types of niches joining the marketplace. This is an ever-evolving and proactive initiative.

# Donation Target

**Donation target:** 20,000 PART

## Includes:

- The full development of the system, its infrastructure, and its deployment.

- The funds required to pay for and host the infrastructure for six (6) months, which includes various servers.

- The automation of the system and its integration on Particl Desktop.

- The setup and management of all required accounts and payment processing solutions. This includes a merchant account, corporate filings, business bank account, eCommerce tool monthly subscriptions, etc. 

- The active management and curating of marketplace content (i.e., products).

- The funds required for six (6) months of product listing (target: 5,000 listings per day).

- The funds required to support BTC, PART, and fiat buffer reserves to ensure the stability, rapidity, and well-functioning of the system without human intervention.

- Donations for time compensation for all involved parties.

## Note

- The development of this initiative is already underway.

- If the donation target isn’t reached, the initiative may be reduced in scope (i.e. number of items, smaller buffer reserves, less automation, etc) so that it can still be deployed using less resources.

# Parties Involved

- **Juha Kovanen (Ludx)** - Development, integration, and maintenance.

- **Cryptoguard** - Management of content, accounts, and filings.

## Note

The development and maintenance process of what's being proposed here is provided as an entirely independent initiative. It is not related to any official Particl or Particl Foundation contribution.

### CODE REVIEW

**Comment by AllienWorks** [comment]
What's not to like?
I'm all in, this is a great win-win approach and I agree that this will make 3.0 explode (in a good way ofc :)

In short, push this to Funding Required ASAP and to quote the popular line: _shut up and take my money!_

**Comment by coybigpart** [comment]
I have some questions:
- Will this be an open source project, so everyone can use it?
- Will it be possible for vendors to integrate their own API's? (Thinking about e-services)
- Will the update interval of the prices be fixed to 24 hours, or is this adjustable?

**Comment by cryptoguard** [comment]
> I have some questions:
> 
>     * Will this be an open source project, so everyone can use it?
> 
>     * Will it be possible for vendors to integrate their own API's? (Thinking about e-services)
> 
>     * Will the update interval of the prices be fixed to 24 hours, or is this adjustable?

Question 1: 

This initiative and its code is not originally intended to be opened up for a few reasons, at least not for its initial release, but we may consider doing it at some point.

One, we'd like to keep it private, at least for a while, to prevent other decentralized marketplaces to re-use the idea and deploy it on their end. Sort of a trade secret. We strongly believe this initiative to be quite important to Particl's adoption and are convinced it'll have a great impact. Other decentralized marketplaces may be interested in porting the concept over to their own project and this may hurt the network effect potential of the V3 release.

Second, there's a bit more than just code involved. This initiative requires various services, servers, and accounts to be integrated, and externally managed, into the system. It also requires quite a good deal of subscriptions and registrations to third-party services. And then, it requires a company to be formed for tax and liability purposes and also to gain the ability to easily process and execute payments, open/manage the accounts needed, manage the buffer reserves on exchanges, and etc. In other words, it is much larger in scope than simply a piece of code that can be deployed in a few clicks.

Third, this system gives the ability to seed an incredibly high number of listings on the marketplace. To ensure this system doesn't end in the wrong hand, resulting in tons of spam listings, we would prefer keeping the code private at least until something like SMSG 2.0 is ready (which will offer better scalability, among other things). SMSG 2.0 is something that Tecnovert has started envisioning, but it's very early and not his primary focus for the moment. Given a decent level of adoption, an SMSG 2.0 will be required anyway, and at this point it may be more secure to release the code publicly.

We are fully open to the idea of, at some point, opening up the code to the community or to some of its trusted members who are serious about deploying an automated vendor of their own. This will require some extra coding, clean up, streamlining, as well as a fair bit of documentation before it can be released. This is not within the scope of this proposal.

Keep note, though, that you should feel free to reach out to us should you be serious about wanting to deploy an automated vendor.

**Question 2:**

I am not sure I understand the question exactly.


Question 3: 

The interval is set at 24 hours, meaning prices will be updated every 24 hours to reflect the correct PART / USD price. It is, however, perfectly adjustable even to lower (a few hours, or even seconds) intervals than this as the system uses the market back-end directly, not Particl Desktop. The reason for this is that the system automates the conversion of crypto/fiat to process orders and execute payments to suppliers and, to ensure the stability of the entire system, we need to make sure that the payments received for orders are as close as possible as the intended USD valuation. There's a risk associated with it which falls on our end, and updating listing prices often does help reduce that risk by a lot.

As a follow up to this question and as a direct result of this initiative being worked on, we are currently exploring integrating the ability to delete a listing into the marketplace codebase. This will allow better listing price management and the ability to protect vendors against wild price swings even more.

**Comment by bacoinin** [comment]
Thank you @cryptoguard and @xludx for this great initiative. 

Regarding the proposal itself, my only comment is that it could be advantageous to spread the listings re-publishing across the daily blocks but I am pretty sure that you are already planning to do that :)  

I also hope that beyond the incredible benefits that your proposal brings to the Particl ecosystem, you will consider developing your particl-market interface further after these 6 months and aim/target to introduce the business world to trust-less decentralized b2b trade.

Cheers! I will strongly support your initiative!

**Comment by cryptoguard** [comment]
> Thank you @cryptoguard and @xludx for this great initiative.
> 
> Regarding the proposal itself, my only comment is that it could be advantageous to spread the listings re-publishing across the daily blocks but I am pretty sure that you are already planning to do that :)
> 
> I also hope that beyond the incredible benefits that your proposal brings to the Particl ecosystem, you will consider developing your particl-market interface further after these 6 months and aim/target to introduce the business world to trust-less decentralized b2b trade.
> 
> Cheers! I will strongly support your initiative!

Yes, this is what we intend on doing. Not only will this spread staking rewards to more stakers but also be much less of a burden on the network itself. To that end, there is currently some preliminary work being done on SMSG 2.0, so the "burden on the network" part of things should be less of a problem somewhere next year once it's ready for release. SMSG 2.0 is very early in the process though (mostly at research and experimentation stage), we'll have more details on that later on in 2021.

**Comment by cryptoguard** [comment]
We will soon be moving this proposal into the Funding Required phase.

If you have any question, feedback, or comment, please do so before the proposal moves after which point it won't be able to be amended.

**Comment by coybigpart** [comment]
Can we know for which vendor this will be developed and what kind of products they are going to sell on the marketplace?

**Comment by cryptoguard** [comment]
> Can we know for which vendor this will be developed and what kind of products they are going to sell on the marketplace?

This isn't being developed for a single vendor in particular. This system is highly modular and allows to feed listings from various sources, websites, suppliers, and etc. The categories that will be seeded are many, we'll be initially focusing on populating a good number of the categories available on Particl Marketplace but might branch out with custom categories for storefronts. The goal is to provide a good base of items for most Particl categories.

**Comment by coybigpart** [comment]
Only suggestion I can do is to wait for the funding phase untill V3 is on testnet. Anyway I will sponsor some parts like always. Good luck with this great idea and addition to the Particl ecosystem.

**Comment by dasource** [comment]
Thanks for clarifying the milestone payouts - moving to funding now, all the best and looking forward to seeing it in action.

**Comment by cryptoguard** [comment]
# Proposal Update (08-02-2022)

Since initially publishing this proposal, a whole lot has changed and affected its development, delivery, and scope; it’s high time for a status update! This update will detail these changes and provide an up-to-date overview of where it currently stands.

### Note 
Although this initiative is dependent on items delivered by the Particl team (i.e., marketplace product codes, SMSG manager, etc), **it is being proposed on a personal basis. It’s development and delivery is not part of the team’s official work scope.**

## Development Status

The proposal initially suggested a delivery time of about 4 weeks, but a few events have delayed and slowed down its progress. 

Among these, the switch from Particl V2 to V3 has taken considerably more time than expected as the scope of the new marketplace codebase (V3) has been significantly expanded while it was being developed. And since this initiative relies entirely on how the marketplace codebase works, deploying it on V2 would have meant that it would have needed a complete refactor in order to be redeployed on Particl V3. For this reason, we opted to delay its release at least until Particl V3 was ready. 

Then, as Particl V3 was being worked on, the developer initially in charge of building this proposed system reduced his level of involvement within the project and has decided handing the responsibilities associated with this proposal off to Arnold Bansemer; Particl Desktop’s lead developer. Arnold is now fully in charge of this initiative’s development.

And, finally, the revised structure of this initiative is dependent on a few technical deliverables. Some of them are now available as of Particl V3, but a few remain to be released. But we've got a solution to deploy this initiative more rapidly.

## System Deployment

With Arnold Bansemer now in charge of this initiative’s development, a new, more encompassing vision for it has been brought forth. Indeed, the underlying structure of the system has been remodeled and has expanded in scope, notably related to how it will ultimately be opened up so that anyone in the community can use it.

In the interest of delivering on its initial objective more promptly (seeding the marketplace with a significant number of listings) and facilitate the adoption of Particl V3, **we’re now opting to deploy the proposal in a few phases, with the first one being imminent, rather than waiting for it to be entirely completed**.

The **first phase** of this initiative will be to populate the marketplace with a significant number of listings. In this phase, there is no automated order processing and also no extracted reviews yet; it rather focuses on gradually increasing the number of listings, which doubles as a real-life stress test of the current SMSG network. At this time, the only requirement still missing for this is the addition of “product codes” into the market codebase and the desktop client. Product codes are unique identifiers attached to individual marketplace listing templates. They let Particl Desktop update already-existing listing templates based on the information contained in CSV files when that information changes (i.e., a new price, description, image, availability, etc). This is different from the current setup where re-importing the same items through CSV files creates duplicates (and quickly bloats a user’s client and reduces performance). This feature is essential for this initiative as listings are expected to be updated very often and is now scheduled for release as part of the upcoming Particl Desktop 3.2 update.

**In later phases**, more automation will be deployed to speed up the process of purchasing an item on the marketplace issued from this initiative. The ability to list items in markets and storefronts other than the Open Market will also be added and reviews will be able to be extracted from the source and imported into the marketplace. As delivering these more advanced features still require a few pre-requisites, notably the SMSG controller and more complex scripts, they will be deployed at a later time in the future. For now, our priority is to deploy phase one promptly and get the ball rolling adoption-wise.

Once all the deliverables of this proposal are released, that’s when this proposal takes a life of its own and **gets opened up to the public**. When that happens, it will be possible for individuals to use this system to manage large numbers of listings and easily process orders themselves. However, this specific phase is highly dependent on how the current SMSG network handles high numbers of listings. Indeed, it may not be safe to open the system to the public if it risks over-stressing the network and causing various problems (especially since the marketplace and BasicSwap both use the same SMSG network), and so, for this reason, we may opt to delay that phase up until SMSG 2.0 is ready.

## Conclusion

At this time, this proposal is actively being worked on and prepared for its initial release. We are happy to announce that it will be ready to deploy (with the number of listings increasing gradually rather than all at once) shortly after the release of the next Particl Desktop update (3.2). 

We apologize for the unfortunate delay in delivering this proposal but are confident that it will satisfy the community’s expectations for it and make the content of the marketplace more interesting and attractive for a wider range of audiences. 

If you have any question, comment, or suggestion, please leave them in the comment section of this proposal. Your feedback is valuable and is critical in steering the ship in the right direction to ensure maximum impact for this proposal.

Thanks for your interest in this proposal!

**Pull request merged**
